apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${EKS_CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "1.26"
vpc:
  id: ${VPC_ID}
iam:
  withOIDC: true
addons:
  - name: aws-ebs-csi-driver
    version: v1.18.0-eksbuild.1
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
managedNodeGroups:
  - name: mng-1
    desiredCapacity: 4
    instanceType: m5.2xlarge
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: false
        ebs: true
